In [2]:
import numpy as np
from sympy import *

a = np.random.randn(3, 4)
b = np.random.randn(4, 1)

c = np.random.randn(3, 4)
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

print(c)
print(a+b.T)


[[-1.26550152 -1.55252621  1.643387    2.9566504 ]
 [-0.49624414 -1.30972986  1.87373886 -0.68788703]
 [-0.89204088 -0.82591204  1.25472796  1.06847844]]
[[-1.26550152 -1.55252621  1.643387    2.9566504 ]
 [-0.49624414 -1.30972986  1.87373886 -0.68788703]
 [-0.89204088 -0.82591204  1.25472796  1.06847844]]


In [3]:
x = Symbol('x')
y = x**2 + 1
yprime = y.diff(x)
print(yprime)

2*x


In [7]:
# Sigmoid

Z = Symbol('Z')
sig = 1/(1+E**(-Z))
sig_prime = sig.diff(Z)
print("Sigmoid ': ", sig_prime)

Sigmoid ':  exp(-Z)/(1 + exp(-Z))**2


In [30]:
# Test 

A = np.random.randint(0, 10, (3, 1))
print(A)
pow_arr = np.array([[1], [2], [3]])
print(pow_arr.shape, A.shape)
(A * pow_arr)

[[1]
 [8]
 [9]]
(3, 1) (3, 1)


array([[ 1],
       [16],
       [27]])

In [24]:
x = Symbol('x')
k = Symbol('k')
power = x ** k
print("func: ", power)
print("dx: ", power.diff(x))
print("dk: ", power.diff(k))

func:  x**k
dx:  k*x**k/x
dk:  x**k*log(x)
